version: 2
jobs:
  build:
    working_directory: /go/src/github.com/envoyproxy/go-control-plane
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: make check
      - run: make compile
      - run: make test
