version: 2
jobs:
  build:
    working_directory: /go/src/github.com/envoyproxy/go-control-plane
    docker:
      - image: rshriram/envoy-go-build:956131ed
    steps:
      - checkout
      - run: make check
      - run: make depend.install
      - run: make compile
      - run: make test
